apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: flask-app
        image: mohammadmasalmeh/flask-mongodb-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5003
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb-service:27017/"
